### ISSUE TITLE
dgsImageGetNativeSize fix

### ISSUE THREAD

**Issue by MartinoFY** [thisdp/dgs#100]
Core/image.lua
![image](https://user-images.githubusercontent.com/87902852/126869828-62a28606-d8b7-4ab8-81a8-bb18ad9c29b0.png)
Fix:
![image](https://user-images.githubusercontent.com/87902852/126869871-c99c57df-e635-4b5d-b7df-a3c4e459af2d.png)

**Comment by xLive** [comment]
Thanks
