### ISSUE TITLE
lag and drop fps

### ISSUE THREAD

**Issue by xLive000** [thisdp/dgs#11]
After a time of running **Dgs** to my server
It has become a lag for all players
performancebrowser say the reason is **Dgs**
but the lag happens and **Dgs** elements are not running i checked it by /debugdgs
sorry for bad english

**Comment by thisdp** [comment]
is Render Time of dgs 0?

**Comment by xLive000** [comment]
10-22

**Comment by thisdp** [comment]
what dgs elements you have created?

**Comment by xLive000** [comment]
The lag occurs and Dgs elements are not created

**Comment by thisdp** [comment]
is there any debug message?

**Comment by xLive000** [comment]
nope

**Comment by thisdp** [comment]
But i can't reproduce it. DGS will lag without elements, very strage. No elements means nothing to render.

**Comment by xLive000** [comment]
Could Dgs events be the reason? I will check it soon

**Comment by thisdp** [comment]
Never had i met with such problem.

**Comment by xLive000** [comment]
see
this screenshot from debugdgs
![mta-screen_2018-04-05_19-21-12](https://user-images.githubusercontent.com/30420446/38379493-874d4a96-3909-11e8-974b-4a9ae7f5e18c.png)
and this from performancebrowser
![screenshot - 05_04_2018 07_38_26](https://user-images.githubusercontent.com/30420446/38379519-9f270c60-3909-11e8-9d9e-249cbebacca3.png)
i have stopped all scripts are using Dgs but nothing happened
when i stopped Dgs the lag gone

**Comment by thisdp** [comment]
amazing

**Comment by thisdp** [comment]
what if you only starts dgs?

**Comment by xLive000** [comment]
i did this and the lag gone

**Comment by thisdp** [comment]
So if you can find out what cause the dgs into lag, I will fix it at once. :D

**Comment by xLive000** [comment]
i have so many scripts but if i find it i will  talk to you

**Comment by thisdp** [comment]
add my skype : thisdpzjl
I want to discuss it with you

**Comment by xLive000** [comment]
done

**Comment by Ahmed-Ly** [comment]
@xLive000  
What is Video Card do you have?

**Comment by xLive000** [comment]
I spoke to thisdp by Skype, thank you
