### ISSUE TITLE
DGS update

### ISSUE THREAD

**Issue by AidisProPlayer** [thisdp/dgs#112]
Hello, I have a problem after the DGS update, nothing is displayed, no errors in db3.

**Comment by thisdp** [comment]
does /debugdgs work?

**Comment by AidisProPlayer** [comment]
Yes and nothing there.

**Comment by thisdp** [comment]
nothing? I mean do you see the debug text on screen after running command "/debugdgs" on client?

**Comment by AidisProPlayer** [comment]
I don't see any text.

**Comment by AidisProPlayer** [comment]
Now i see.

**Comment by thisdp** [comment]
If you can see the debug text on screen, clientsided script is running.

**Comment by thisdp** [comment]
after updating dgs, you should restart dgs and then restart all of your scripts

**Comment by AidisProPlayer** [comment]
edit = DGS:dgsCreateEdit(0.410, 0.567, 0.165, 0.04, "", true)   
DGS:dgsSetVisible(edit, false)

But I can't see it and much more.

**Comment by thisdp** [comment]
did you do this?
DGS = exports.dgs

**Comment by AidisProPlayer** [comment]
I have this.

**Comment by thisdp** [comment]
run command /debugdgs
if there is a edit created, in dgs debug, there will be:
dgs-dxeditor: 1

**Comment by AidisProPlayer** [comment]
Where i must put dgs-dxeditor: 1?

**Comment by thisdp** [comment]
no it should be on your screen in dgs debug mode

**Comment by AidisProPlayer** [comment]
I have dgs-dxedit: 9

**Comment by thisdp** [comment]
you can't see those edits?

**Comment by AidisProPlayer** [comment]
Yes.

**Comment by thisdp** [comment]
ok. come to our discord, I will be there: https://discord.gg/QEs8q6W

**Comment by thisdp** [comment]
dgsSetRenderSetting("postGUI",true) should fix this
