### ISSUE TITLE
TabPanel issue

### ISSUE THREAD

**Issue by 538Michael** [thisdp/dgs#115]
Hello, everything was working correctly, but when I inserted TabPanel method utility.lua returns an error. It was working on my old version 3.5, but when I updated to 3.517 this happens.

![image](https://user-images.githubusercontent.com/4532464/177194669-88f9bb26-37eb-4018-aead-fb05cdba31af.png)
![image](https://user-images.githubusercontent.com/4532464/177194791-61fcf3e0-6545-41e5-8f85-150361e65234.png)

**Comment by thisdp** [comment]
Fixed
