### ISSUE TITLE
DGS does a memory leak (Streaming video card etc.. a lot of kb and even after closing it doesn't get better)

### ISSUE THREAD

**Issue by RecuvaPumDEV** [thisdp/dgs#128]
Hello, I just want to point out and also ask how should I delete all ELEMENTS when DGS elements are deleted using destroyElement but the KB still remains in Lua Memory, for example, in a few windows it is added but then deleted again, but after spamming the given script, the MTA subsequently crashes and or the images (dxCreateTexture) or (dgsCreateImage) are not shown at first, so after spamming that script, they do not show after a while and become white, and then the MTA client crashes. I'm asking for help on how to improve this and make it so that all elements are removed, I'm using the mod for RolePlay, more precisely OWLGAMING 2020, which is almost entirely redone by Odem and another scripter and is also de facto completely changed to DGS, so as I say please help or simply how to remove that save from DGS.

**Comment by thisdp** [comment]
dgs won't handle the textures that is not created by dgs

**Comment by thisdp** [comment]
https://wiki.multitheftauto.com/wiki/DgsAttachToAutoDestroy
but at least you can use this
