### ISSUE TITLE
Add property to change ComboBox item vertical spacing

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [thisdp/dgs#130]
Currently, you can control [itemTextPadding](https://wiki.multitheftauto.com/wiki/Dgs-dxcombobox#itemTextPadding), which appears to work as it offsets the item text from the left. However, I wasn't able to increase the spacing between items. As you can see in the screenshot, I'm using a rather big [font](https://wiki.multitheftauto.com/wiki/Dgs-dxcombobox#font) so the item texts touch each other, and it could use some spacing.

![image](https://github.com/thisdp/dgs/assets/34967844/94d24a26-7038-457a-8cb1-af9542629a86)

**Comment by thisdp** [comment]
use ItemHeight
