### ISSUE TITLE
Simple problem ^^"

### ISSUE THREAD

**Issue by xfresco** [thisdp/dgs#134]
https://github.com/thisdp/dgs/blob/f6e2dc39f8f8ad3e2f0b4d49592c92aeaaed89a4/plugin/Gradient/gradient.lua#L20

> 	assert(type(colorFrom) == "number","Bad argument @dgsGetGradientColor at argument 2, expect number got "..type(**color1**))
	assert(type(**color2**) == "number","Bad argument @dgsGetGradientColor at argument 3, expect number got "..type(**color2**))

function dgsGradientSetColor(gradShader,colorFrom,colorTo)
	assert(dgsGetPluginType(gradShader) == "dgs-dxgradient","Bad argument @dgsGradientSetColor at argument 1, expect dgs-dxgradient got "..type(gradShader))
	assert(type(colorFrom) == "number","Bad argument @dgsGetGradientColor at argument 2, expect number got "..type(**colorFrom**))
	assert(type(**colorTo**) == "number","Bad argument @dgsGetGradientColor at argument 3, expect number got "..type(**colorTo**))
	dgsSetData(gradShader,"colorFrom",colorFrom)
	dgsSetData(gradShader,"colorTo",colorTo)
	dxSetShaderValue(gradShader,"colorFrom",{fromcolor(colorFrom,true,true)})
	dxSetShaderValue(gradShader,"colorTo",{fromcolor(colorTo,true,true)})
	return true 
end

**Comment by thisdp** [comment]
fixed
