### ISSUE TITLE
Creating memo with relative size doesn't work

### ISSUE THREAD

**Issue by R3fr3Sh** [thisdp/dgs#2]
As the title says, I am unable to create memo with relative size, but I fixed my problem with one line of code added at line 55 in file core/memo.lua. I'd create pull request but I don't know how can I do that.
local renderTarget = dxCreateRenderTarget(abx-4,aby,true)

**Comment by thisdp** [comment]
Show me your code.

**Comment by thisdp** [comment]
memo = dgsDxCreateMemo(0.2,0.2,0.4,0.4,"This is a dgs-dxmemo",true)
This works fine.

**Comment by R3fr3Sh** [comment]
I even updated dgs to latest version using console.
local DGS = exports.dgs; DGS:dgsDxCreateMemo(0.2,0.2,0.4,0.4,"This is a dgs-dxmemo created using relative size",true)
local DGS = exports.dgs; DGS:dgsDxCreateMemo(900, 500, 200, 100, "This is a dgs-dxmemo created using real size", false)

Result:
![screen](https://user-images.githubusercontent.com/25273433/34439983-541a046e-ecb2-11e7-8a8c-d2b8f892c1c3.jpg)

**Comment by thisdp** [comment]
Check your video memory. If your video memory is low, you can't create memo.
