### ISSUE TITLE
Suggestion Theme

### ISSUE THREAD

**Issue by AbdelrahmanHamdyR** [thisdp/dgs#20]
Hello friends, what do you think about modifying the theme of the game ?!
We make it with dgs technology
An example is taken and modified.
![cgui](https://user-images.githubusercontent.com/33987614/43860389-3a45cb82-9b5c-11e8-9c69-25d48c07865a.png)

**Comment by CrosRoad95** [comment]
`dgs technology` XD

**Comment by thisdp** [comment]
DGS is not technology

**Comment by thisdp** [comment]
Make your theme yourself.
