### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by 4O4** [thisdp/dgs#27]
Hi there, I really liked the project since the first time I stumbled upon it a while back. I also love the fact that it is still under active development 👍 Sadly there is almost no chance for me to use DGS because of the license which requires me to disclose source code of any program which would use it. Is there any chance for re-license or dual-license under less restrictive terms?

**Comment by 4O4** [comment]
I'm not taking about dgs code which I would be more than happy to
contribute back. I'm talking about any of my code which would use dgs.
GPLv3 (unlike MIT for example) basically obligates you to publish all your
private codebase utilizing this library. I guess your intention was to
ensure back-contributions to dgs itself but GPLv3 is far more than that -
it's very limiting in reality.

**Comment by thisdp** [comment]
and,now?

**Comment by 4O4** [comment]
Please release the lib under non-copyleft license like BSD or MIT which
don't force the developer to publish all of their derivative work under the
same license terms and thus give more freedom :)

**Comment by thisdp** [comment]
Now dgs is only protected by DPL lol

**Comment by 4O4** [comment]
I'm sorry but you seem to not understand the terms of GPL even though I'm
trying hard to explain them as simply as possible. It is not 'only' GPL. If
you create any project using DGS, let's say it's a login panel, you have an
obligation to release the login panel source code under the same license.
Thats how it works and that's a no-go for many devs.

**Comment by 4O4** [comment]
Uh I see now, DPL you say... I thought it was a typo 🙂 This license is pretty unclear for me now, could you extend it to include more information what is actually allowed in the terms of usage by other resources and and not only in the terms of modifying the lib code?

**Comment by thisdp** [comment]
Items not mentioned are allowed!!!

**Comment by thisdp** [comment]
Let's fuck the GPL and MIT

**Comment by 4O4** [comment]
Ok, so just state this in the readme so it's clear for everyone. Also there are many others, including fun ones like WTFPL 😁

**Comment by thisdp** [comment]
:D

**Comment by 4O4** [comment]
Thank you for your time on this one, keep up the good work
