### ISSUE TITLE
Make small circular progress bar antialiased

### ISSUE THREAD

**Issue by saml1er** [thisdp/dgs#42]
**The problem:**

When I create a small circular progress bar, the edges are not smooth. 

**Code to produce the bug:**

```local progressBar = dgsCreateProgressBar(800, 400, 130, 130, false)
dgsSetProperty(progressBar,"bgColor", tocolor(0, 0, 0, 255))
dgsProgressBarSetStyle(progressBar,"ring-round")
local progress = 0
addEventHandler("onClientRender", root,
    function()
    dgsProgressBarSetProgress(progressBar,progress)
    progress = progress + 0.1
end)
```

**Screenshot:**
![circle](https://user-images.githubusercontent.com/10183157/74603839-ac79a500-50d9-11ea-9db6-7c5ae4ab39d0.png)

**Comment by thisdp** [comment]
Fixed. Thanks

**Comment by saml1er** [comment]
> 
> 
> Fixed. Thanks
> ![3~GU2`OY%2B%BIUML0}4L 2](https://user-images.githubusercontent.com/30386052/74604152-2c156d00-50f6-11ea-8a83-d0af59c05711.png)

That was fast. Thank you. :)
