### ISSUE TITLE
Some Dgs elements not shown

### ISSUE THREAD

**Issue by xLive000** [thisdp/dgs#5]
Hello
Some players do not show Dgs elements for them
they can't see Dgs label and tabpanel just empty window and another script also memo
and i'm sure my code is working fine
please try fix it soon i don't want back to gui

This images is taken from a player who has the problem
![scripterror](https://user-images.githubusercontent.com/30420446/35634145-03e3f24c-06bc-11e8-8327-c4eeb98c185b.png)
![scripterror2](https://user-images.githubusercontent.com/30420446/35634718-670c9b66-06bd-11e8-9975-e984cb5b8145.png)
Thank you.
Sorry for the bad English

**Comment by thisdp** [comment]
This is because their video memory is so low that render target can't be created.

**Comment by xLive000** [comment]
Is there any way to fix it ? it's a big problem.

**Comment by xLive000** [comment]
Okey, thank you so much :D
