### ISSUE TITLE
edit box cursor

### ISSUE THREAD

**Issue by nelsonjrr23** [thisdp/dgs#63]
them i apply the code : 

DGS:dgsSetVisible( Edit, false )
DGS:dgsFocus(image1)
DGS:dgsSetEnabled ( Edit, false )

disappears correctly but cursor still on screen. only clicking somewhere the cursor show off. 
Who can i do to cursor show off with the dgsSetVisible   false.

another thing is if i m in car doing this  the edit box dont type the letters

**Comment by thisdp** [comment]
I can't reproduce that

**Comment by thisdp** [comment]
Could you offer the complete code that can reproduce it?

**Comment by xLive** [comment]
I guess it's invalid since the owner didn't respond for weeks and no one couldn't reproduce it
