### ISSUE TITLE
Error when using dgsMemoSetVerticalScrollPosition

### ISSUE THREAD

**Issue by xLive** [thisdp/dgs#64]
![image](https://user-images.githubusercontent.com/30420446/89932693-b4447d00-dc16-11ea-993c-5c50f784c6f9.png)

**Comment by xLive** [comment]
Another error when i'm selecting text idk if related to the previous error:
![image](https://user-images.githubusercontent.com/30420446/89935381-c32d2e80-dc1a-11ea-8bd1-f1c93903f336.png)

**Comment by thisdp** [comment]
Fixed
