### ISSUE TITLE
colorScheme backup (/updatedgs)

### ISSUE THREAD

**Issue by AleksCore** [thisdp/dgs#7]
How /updatedgs should work in my opinion:
- it should rename my current colorScheme.txt to colorScheme.txt.backup and download new colorScheme as colorScheme.txt

How it works at the moment:
- it keeps colorScheme.txt untouched and new colorScheme will be colorScheme.txt.backup

**Comment by thisdp** [comment]
First backup the file. Then keep the settings and add new settings if latest dgs have into the colorScheme.txt.
