### ISSUE TITLE
ComboBox drop-down box width does not update after changing its height

### ISSUE THREAD

**Issue by xLive** [thisdp/dgs#71]
**To reproduce:**
```lua
local combo = dgsCreateComboBox(0,0,280,30,"Test") 
dgsCenterElement(combo) 
for i=1,10 do 
dgsComboBoxAddItem(combo,i) end 
dgsComboBoxSetBoxHeight(combo,40) 
dgsSetSize(combo,320,30)
```

![image](https://user-images.githubusercontent.com/30420446/90295882-c0d50980-de92-11ea-855f-358816be00b0.png)

**Comment by xLive** [comment]
After some searching

`onDgsSizeChange` event doesn't trigger for the drop-down box at all if you have a custom height for the box

**Comment by thisdp** [comment]
fixed
