### ISSUE TITLE
3dInterfaces appear black after version 3.468

### ISSUE THREAD

**Issue by PlatinMTA** [thisdp/dgs#72]
After updating my DGS to the lastest version I discovered that 3dInterfaces (or at least 3dInterfaces with windows) now appear black.

<details>
  <summary>Click me to see the images</summary>

How it looks in 3.494 onwards
![](https://i.imgur.com/njyOWLl.png)

How it should look
![](https://i.imgur.com/uIOs6AZ.png)
</details>

I have no clue what the issue is, but 3.468 works just fine

**Comment by xLive** [comment]
hmmm can you upload 3.468 verison?
 i need to test cuz i did some tests and didn't work

**Comment by PlatinMTA** [comment]
I got it form the releases of this github: https://github.com/thisdp/dgs/releases/tag/3.468

**Comment by thisdp** [comment]
nah, 3.468 uses material line 3d, while after 3.468 uses material primitive line 3d

**Comment by PlatinMTA** [comment]
#73 does fix the error.
