### ISSUE TITLE
OOP PostGUI always TRUE

### ISSUE THREAD

**Issue by 538Michael** [thisdp/dgs#74]
When using OOP all elements are always postGUI TRUE, even using :setPostGUI(false). POP version (dgsSetPostGUI) works fine.

I'm using wiki OOP window example, adding **:setPostGUI(false)**

```
 loadstring(exports.dgs:dgsImportOOPClass(true))()-- load OOP class
 window = dgsWindow(0,0,0.5,0.1,"test",true):setPostGUI(false) --create a window with oop
 label = window:dgsLabel(0,0,1,1,"label",true) --create a label inside the window ( Correct )
 label.text = "DGS OOP Test" --set text
```

**Comment by 538Michael** [comment]
Found why. In classlib.lua there's:

```
setPostGUI = dgsOOP.genOOPFnc("dgsGetPostGUI",true),
```

Should be:

```
setPostGUI = dgsOOP.genOOPFnc("dgsSetPostGUI",true),
```

**But now another issue:**
It just applies the postGUI to the element and not to the whole children.

**Comment by thisdp** [comment]
fixed
