### ISSUE TITLE
Scrollbar in gridlist bug

### ISSUE THREAD

**Issue by Bartelek** [thisdp/dgs#78]
When i both left mouse button and click the right or middle mouse button on scroll bar, on debugscript3 appears: ERROR: dgs\Core\scrollbar.lua:274: attempt to index field 'MoveScroll' (a boolean value)

![image](https://user-images.githubusercontent.com/73140021/96510009-2f509200-125d-11eb-8aa9-ac07870ac774.png)

**Comment by xLive** [comment]
I think it should work only with the left click button like everything else? @thisdp

**Comment by Bartelek** [comment]
Yes

**Comment by thisdp** [comment]
> I think it should work only with the left click button like everything else? @thisdp

DGS 's right clicking is regarded as "custom-able". But here, we should only check the left clicking

**Comment by thisdp** [comment]
fixed
