### ISSUE TITLE
Layouts system

### ISSUE THREAD

**Issue by 4O4** [thisdp/dgs#80]
Hi, do you have any plans to implement a system for automatic layout of GUI components? Here are some examples of the idea from GUI toolkits in other languages:

- Java Swing layout managers: https://docs.oracle.com/javase/tutorial/uiswing/layout/visual.html
- QT Layout Management: https://doc.qt.io/qt-5/layout.html https://www.learnpyqt.com/tutorials/qt-designer-gui-layout/
- GTK Layout Managers and Layout Containers: https://developer.gnome.org/gtk4/stable/LayoutManagers.html https://developer.gnome.org/gtk3/stable/LayoutContainers.html
- wxWidgets Layout Management: https://brucey.net/programming/blitz/tutorials/prog/en/layoutmanagement.html https://www.tutorialspoint.com/wxpython/wxpython_layout_management.htm
- Flutter layout widgets: https://flutter.dev/docs/development/ui/layout#common-layout-widgets
- WPF Layouts: https://www.wpftutorial.net/LayoutProperties.html
- Fyne (Go GUI library) layouts: https://developer.fyne.io/tour/layout/ (the docs aren't very nice, please note that you have next page buttons at the bottom, and also there are different sections of the documentation describing the layouts and custom layout creation: https://developer.fyne.io/tutorial/custom-layout )

What do you think about it? Could such layouting concept land in the DGS? I think it would be a great feature and would speed up GUI development a bit but it would probably take some good amount of time to implement it well.

**Comment by thisdp** [comment]
https://github.com/thisdp/dgs/commit/83f5ada9342c9fb42843d43a6e92c85cdae71be8

**Comment by thisdp** [comment]
done
