### ISSUE TITLE
It appears that r20765 broke DGS

### ISSUE THREAD

**Issue by PlatinMTA** [thisdp/dgs#88]
~~On the nightly that did [this change to the textures](https://github.com/multitheftauto/mtasa-blue/commit/4ca4601ac3b044cea418238fa34eb51f18c9ef00) something broke in DGS.~~ No debug message appears, but I am unable to close any window or even move them correctly.

In r20762 it works just fine. ~~I didn't test other versions, but I suspect that [this](https://github.com/multitheftauto/mtasa-blue/commit/4ca4601ac3b044cea418238fa34eb51f18c9ef00) or [probably this](https://github.com/multitheftauto/mtasa-blue/commit/c4b9a844c3dc8f8fd16776370dcdac12f189d32f) broke DGS.~~

Video about the issue: https://youtu.be/OvjEY4L7khI

If it can't be fixed due to being a problem with MTA I could make an issue about it, but I didn't take the time to dissect the problem or read the DGS code.

EDIT: The bug starts happening on r20765. I think it's related to the editbox since DGS brakes after seeing one afaik.

[This could be the issue.](https://github.com/multitheftauto/mtasa-blue/pull/1944)

**Comment by thisdp** [comment]
the update directly blocked key hold detect when dgs-edit is focused

**Comment by xLive** [comment]
It should be fixed in the next build https://github.com/multitheftauto/mtasa-blue/commit/880e17c9aa234dce330dbc5f6419ee073d6ada2c

**Comment by botder** [comment]
Issue should be fixed after revision 20773
