### ISSUE TITLE
Problem with edit

### ISSUE THREAD

**Issue by ShuffleGTAO** [thisdp/dgs#99]
Hi
i have a trouble with dgs
i used dgs to a custom chat and when i'm trying to write after a turn on writing, dgs is "blocked" and i cant write
i'm using dgs to a loginpanel and everything is ok, only in custom chat is problem

Line of creating : 
typing_message=exports.dgs:dgsCreateEdit((28/1920)*s.x, (348/1080)*s.y, (277/1920)*s.x, (30/1080)*s.y,"",false,false,tocolor(0,0,0,255),1,1,false,tocolor(0,0,0,0))

turn on writing

addEventHandler("onClientKey",root,function(button,state)
          if button=="t" and not state and not typing then
                toggleAllControls(false)
                exports.dgs:dgsSetVisible(typing_message,true)
                exports.dgs:dgsFocus(typing_message)
                exports.dgs:dgsSetFont(typing_message,font_dgs)
                exports.dgs:dgsSetText(typing_message,"")
                typing=true
                showCursor(false)

and when i taped "t", i cant write in this edit
not always, 50/50, one time i can and one time i cant

i use this version

https://community.multitheftauto.com/index.php?p=resources&s=details&id=14420

i dont wanna to update to latest version, because size of text in edit in new version dont working in dgsCreateEdit

**Comment by xLive** [comment]
I can't reproduce this issue in the latest version,
maybe you don't set these variables to false when you finish the typing?
>if button=="t" and not state and not typing then

Also,
> i dont wanna to update to latest version, because size of text in edit in new version dont working in dgsCreateEdit

You can change the text size using the [textSize](https://wiki.multitheftauto.com/wiki/Dgs-dxedit#textSize) property
